### ISSUE TITLE
Blank screen after selecting files

### ISSUE THREAD

**Issue by elogicuk** [abinthomasonline/repo2txt#9]
I downloaded your repo opened the local.html file and try to use the app

and i get a blank screen after selecting my files to upload

![image](https://github.com/user-attachments/assets/0cd33f00-b6f8-498c-b439-c96dc0dc484d)

**Comment by abinthomasonline** [comment]
I see you opened local.html file in the browser, which prevents access to assets like `local.js` due to CORS policy.
<img width="1708" alt="image" src="https://github.com/user-attachments/assets/2ae82a07-192f-4751-880e-73b0410feb06">

Either open in a local server or use directly from the [hosted path](https://repo2txt.simplebasedomain.com/local.html)

To start local server :- `python -m http.server 5500 --directory .`

**Comment by elogicuk** [comment]
thank you its working now
